spring.application.name=taskmanager

#h2 configuration
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

#jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
